// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/boards/boards.proto

package boards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "github.com/AlexMickh/scrum-protos/pkg/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_proto_boards_boards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_boards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_boards_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_proto_boards_boards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_boards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_boards_boards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBoardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_proto_boards_boards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_boards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_boards_proto_rawDescGZIP(), []int{2}
}

func (x *GetBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tasks         []*types.Task          `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_proto_boards_boards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_boards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_boards_boards_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBoardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBoardResponse) GetTasks() []*types.Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_proto_boards_boards_proto protoreflect.FileDescriptor

const file_proto_boards_boards_proto_rawDesc = "" +
	"\n" +
	"\x19proto/boards/boards.proto\x12\x06boards\x1a\x17proto/types/types.proto\"*\n" +
	"\x12CreateBoardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"%\n" +
	"\x13CreateBoardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fGetBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x10GetBoardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\x05tasks\x18\x04 \x03(\v2\v.types.TaskR\x05tasks2\x8f\x01\n" +
	"\x06Boards\x12F\n" +
	"\vCreateBoard\x12\x1a.boards.CreateBoardRequest\x1a\x1b.boards.CreateBoardResponse\x12=\n" +
	"\bGetBoard\x12\x17.boards.GetBoardRequest\x1a\x18.boards.GetBoardResponseB\x10Z\x0epkg/api/boardsb\x06proto3"

var (
	file_proto_boards_boards_proto_rawDescOnce sync.Once
	file_proto_boards_boards_proto_rawDescData []byte
)

func file_proto_boards_boards_proto_rawDescGZIP() []byte {
	file_proto_boards_boards_proto_rawDescOnce.Do(func() {
		file_proto_boards_boards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_boards_boards_proto_rawDesc), len(file_proto_boards_boards_proto_rawDesc)))
	})
	return file_proto_boards_boards_proto_rawDescData
}

var file_proto_boards_boards_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_boards_boards_proto_goTypes = []any{
	(*CreateBoardRequest)(nil),  // 0: boards.CreateBoardRequest
	(*CreateBoardResponse)(nil), // 1: boards.CreateBoardResponse
	(*GetBoardRequest)(nil),     // 2: boards.GetBoardRequest
	(*GetBoardResponse)(nil),    // 3: boards.GetBoardResponse
	(*types.Task)(nil),          // 4: types.Task
}
var file_proto_boards_boards_proto_depIdxs = []int32{
	4, // 0: boards.GetBoardResponse.tasks:type_name -> types.Task
	0, // 1: boards.Boards.CreateBoard:input_type -> boards.CreateBoardRequest
	2, // 2: boards.Boards.GetBoard:input_type -> boards.GetBoardRequest
	1, // 3: boards.Boards.CreateBoard:output_type -> boards.CreateBoardResponse
	3, // 4: boards.Boards.GetBoard:output_type -> boards.GetBoardResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_boards_boards_proto_init() }
func file_proto_boards_boards_proto_init() {
	if File_proto_boards_boards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_boards_boards_proto_rawDesc), len(file_proto_boards_boards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_boards_boards_proto_goTypes,
		DependencyIndexes: file_proto_boards_boards_proto_depIdxs,
		MessageInfos:      file_proto_boards_boards_proto_msgTypes,
	}.Build()
	File_proto_boards_boards_proto = out.File
	file_proto_boards_boards_proto_goTypes = nil
	file_proto_boards_boards_proto_depIdxs = nil
}
