// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/tasks/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	types "github.com/AlexMickh/scrum-protos/pkg/api/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTaskResponse) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *CreateTaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskResponse) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type GetAllTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*types.Task          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTasksResponse) Reset() {
	*x = GetAllTasksResponse{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTasksResponse) ProtoMessage() {}

func (x *GetAllTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTasksResponse.ProtoReflect.Descriptor instead.
func (*GetAllTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllTasksResponse) GetTasks() []*types.Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTasksByBoardIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksByBoardIDRequest) Reset() {
	*x = GetTasksByBoardIDRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksByBoardIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksByBoardIDRequest) ProtoMessage() {}

func (x *GetTasksByBoardIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksByBoardIDRequest.ProtoReflect.Descriptor instead.
func (*GetTasksByBoardIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksByBoardIDRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ChangeBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardId       string                 `protobuf:"bytes,2,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeBoardRequest) Reset() {
	*x = ChangeBoardRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBoardRequest) ProtoMessage() {}

func (x *ChangeBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBoardRequest.ProtoReflect.Descriptor instead.
func (*ChangeBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *types.Task            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskResponse) GetTask() *types.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_tasks_tasks_proto protoreflect.FileDescriptor

const file_proto_tasks_tasks_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tasks/tasks.proto\x12\x05tasks\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17proto/types/types.proto\"\x9e\x01\n" +
	"\x11CreateTaskRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xaf\x01\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"8\n" +
	"\x13GetAllTasksResponse\x12!\n" +
	"\x05tasks\x18\x01 \x03(\v2\v.types.TaskR\x05tasks\"5\n" +
	"\x18GetTasksByBoardIDRequest\x12\x19\n" +
	"\bboard_id\x18\x01 \x01(\tR\aboardId\"\x93\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"?\n" +
	"\x12ChangeBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bboard_id\x18\x02 \x01(\tR\aboardId\"5\n" +
	"\x12UpdateTaskResponse\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.types.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xa4\x03\n" +
	"\x05Tasks\x12A\n" +
	"\n" +
	"CreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12A\n" +
	"\vGetAllTasks\x12\x16.google.protobuf.Empty\x1a\x1a.tasks.GetAllTasksResponse\x12P\n" +
	"\x11GetTasksByBoardID\x12\x1f.tasks.GetTasksByBoardIDRequest\x1a\x1a.tasks.GetAllTasksResponse\x12A\n" +
	"\n" +
	"UpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x19.tasks.UpdateTaskResponse\x12@\n" +
	"\vChangeBoard\x12\x19.tasks.ChangeBoardRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"DeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x16.google.protobuf.EmptyB\x0fZ\rpkg/api/tasksb\x06proto3"

var (
	file_proto_tasks_tasks_proto_rawDescOnce sync.Once
	file_proto_tasks_tasks_proto_rawDescData []byte
)

func file_proto_tasks_tasks_proto_rawDescGZIP() []byte {
	file_proto_tasks_tasks_proto_rawDescOnce.Do(func() {
		file_proto_tasks_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tasks_tasks_proto_rawDesc), len(file_proto_tasks_tasks_proto_rawDesc)))
	})
	return file_proto_tasks_tasks_proto_rawDescData
}

var file_proto_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tasks_tasks_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),        // 0: tasks.CreateTaskRequest
	(*CreateTaskResponse)(nil),       // 1: tasks.CreateTaskResponse
	(*GetAllTasksResponse)(nil),      // 2: tasks.GetAllTasksResponse
	(*GetTasksByBoardIDRequest)(nil), // 3: tasks.GetTasksByBoardIDRequest
	(*UpdateTaskRequest)(nil),        // 4: tasks.UpdateTaskRequest
	(*ChangeBoardRequest)(nil),       // 5: tasks.ChangeBoardRequest
	(*UpdateTaskResponse)(nil),       // 6: tasks.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),        // 7: tasks.DeleteTaskRequest
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*types.Task)(nil),               // 9: types.Task
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_proto_tasks_tasks_proto_depIdxs = []int32{
	8,  // 0: tasks.CreateTaskRequest.deadline:type_name -> google.protobuf.Timestamp
	8,  // 1: tasks.CreateTaskResponse.deadline:type_name -> google.protobuf.Timestamp
	9,  // 2: tasks.GetAllTasksResponse.tasks:type_name -> types.Task
	8,  // 3: tasks.UpdateTaskRequest.deadline:type_name -> google.protobuf.Timestamp
	9,  // 4: tasks.UpdateTaskResponse.task:type_name -> types.Task
	0,  // 5: tasks.Tasks.CreateTask:input_type -> tasks.CreateTaskRequest
	10, // 6: tasks.Tasks.GetAllTasks:input_type -> google.protobuf.Empty
	3,  // 7: tasks.Tasks.GetTasksByBoardID:input_type -> tasks.GetTasksByBoardIDRequest
	4,  // 8: tasks.Tasks.UpdateTask:input_type -> tasks.UpdateTaskRequest
	5,  // 9: tasks.Tasks.ChangeBoard:input_type -> tasks.ChangeBoardRequest
	7,  // 10: tasks.Tasks.DeleteTask:input_type -> tasks.DeleteTaskRequest
	1,  // 11: tasks.Tasks.CreateTask:output_type -> tasks.CreateTaskResponse
	2,  // 12: tasks.Tasks.GetAllTasks:output_type -> tasks.GetAllTasksResponse
	2,  // 13: tasks.Tasks.GetTasksByBoardID:output_type -> tasks.GetAllTasksResponse
	6,  // 14: tasks.Tasks.UpdateTask:output_type -> tasks.UpdateTaskResponse
	10, // 15: tasks.Tasks.ChangeBoard:output_type -> google.protobuf.Empty
	10, // 16: tasks.Tasks.DeleteTask:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_tasks_tasks_proto_init() }
func file_proto_tasks_tasks_proto_init() {
	if File_proto_tasks_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tasks_tasks_proto_rawDesc), len(file_proto_tasks_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tasks_tasks_proto_goTypes,
		DependencyIndexes: file_proto_tasks_tasks_proto_depIdxs,
		MessageInfos:      file_proto_tasks_tasks_proto_msgTypes,
	}.Build()
	File_proto_tasks_tasks_proto = out.File
	file_proto_tasks_tasks_proto_goTypes = nil
	file_proto_tasks_tasks_proto_depIdxs = nil
}
